### ISSUE TITLE
Version intl (0.16.1)

### ISSUE THREAD

**Issue by linhadiretalipe** [Appdynamics/flutter-plugin#41]
I am using Flutter 2 in my project I use the lib intl. I had to update the version to intl 0.17.0 because another library updated to this version to work with flutter 2. When I tried to use the appydinamics lib the version of intl is 0.16.1. Please could you update the intl version to 0.7.0?

**Comment by svrnm** [comment]
would you mind providing a Pull Request for this, so I can merge? Otherwise I'll get back to this early next week

**Comment by linhadiretalipe** [comment]
I tried but, but I got this erro fatal: unable to access 'https://github.com/Appdynamics/flutter-plugin.git/': The requested URL returned error: 403, but I will try again.

**Comment by svrnm** [comment]
This should be fixed now, can you confirm @linhadiretalipe ?

**Comment by kuyazee** [comment]
Any updates on this, @linhadiretalipe

**Comment by linhadiretalipe** [comment]
Hi, I really don't know.  Unfortunately  I am not using appdynamics any
more.

**Comment by svrnm** [comment]
This was fixed and I got no further complaints about it, @kuyazee if you are facing any new issues with it, please open a new issue for it, thanks.
