### ISSUE TITLE
adeum-config: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by dolpheen** [Appdynamics/flutter-plugin#43]
There is an error on AD initialization for release and debug mode on Android
Plugin version is 1.0.0
 
[adeum-config- open failed- ENOENT (No such file or directory).log](https://github.com/Appdynamics/flutter-plugin/files/6309483/adeum-config-.open.failed-.ENOENT.No.such.file.or.directory.log)

**Comment by svrnm** [comment]
Hi @dolpheen , 
is this error causing any trouble? This error comes from the underlying android SDK and is not related to the flutter plugin, so I can not fix this from here.

**Comment by dolpheen** [comment]
> Hi @dolpheen ,
> is this error causing any trouble? This error comes from the underlying android SDK and is not related to the flutter plugin, so I can not fix this from here.

Hi, @svrnm 
Looks like everything is OK))
I will try to check AD SDK issues.
