### ISSUE TITLE
nullsafety version

### ISSUE THREAD

**Issue by jWinterDay** [Appdynamics/flutter-plugin#44]
Hello

Are you planning to migrate to nullsafety version?

**Comment by svrnm** [comment]
@jWinterDay can you give me a little bit more details on what you mean by that?

**Comment by jWinterDay** [comment]
I mean upgrade dart sdk version to ">=2.12.0 <3.0.0" in pubspec.yaml
We will update our project to sound nullsafety version and every plugin must be nullsafety version (sdk > 2.12)

**Comment by svrnm** [comment]
Ah, okay, understood.

> I mean upgrade dart sdk version to ">=2.12.0 <3.0.0" in pubspec.yaml

feel free to provide me with a pull request with the required changes and I can merge it into the project and make a new release on pub.dev

**Comment by jWinterDay** [comment]
ok, I'll make it asap

**Comment by jWinterDay** [comment]
Please check this PR https://github.com/Appdynamics/flutter-plugin/pull/45

**Comment by lohnn** [comment]
As this thread have been quiet for more than one month, I have created a PR for this myself. Did not include updating the native parts of the example applications as that should be a PR by itself.
Please have a look at #46.

**Comment by svrnm** [comment]
@lohnn @jWinterDay I was away for some weeks, I can look into it now. I have now two PRs #45 and #46, both solving the same issue apparently. If you have a few minutes can you check the differences and we can discuss what to merge, what not and what is maybe still missing.

**Comment by ranjit-novartis** [comment]
I have downloaded the code from PR#45 and tested by integrating with my app and its working as expected.

Please merge this code asap to unblock the integration with our applications.

**Comment by svrnm** [comment]
@ranjit-novartis, thanks for checking, I merged #45 now. I will do a release as well soon.

**Comment by svrnm** [comment]
https://pub.dev/packages/appdynamics_mobilesdk is now on 2.0.0 with null-safety

**Comment by jWinterDay** [comment]
beautiful, thanks!

**Comment by lohnn** [comment]
Great! Then I'm closing mine now that the other one is merged 👍
