### ISSUE TITLE
Disable Appdynamics for webview

### ISSUE THREAD

**Issue by dolpheen** [Appdynamics/flutter-plugin#47]
Hi!

We have a rangeError exception while opening angular webpage in iOS webview.
Is there a way to disable script injection in webview?

**Comment by svrnm** [comment]
script injection in the webview is happening through the AppDynamics SDK and possible ways to configure it are outlined in the documentation: https://docs.appdynamics.com/21.11/en/end-user-monitoring/mobile-real-user-monitoring/get-more-information-about-mobile-rum/hybrid-application-support
